version: "3.3"
services:
  shadowsocks-rust:
    ports:
      - "0.0.0.0:25117:25117"
      - "0.0.0.0:25117:25117/udp"
    container_name: shadowsocks
    restart: always
    volumes:
      - "/etc/shadowsocks-rust:/etc/shadowsocks-rust"
    image: teddysun/shadowsocks-rust
